version: '3'
services:
  tad:
    image: postgres
    container_name: 'postgres'
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - ${PG_PORT}:5432
